using NUnit.Framework;

//// ncrunch: rdi off
namespace MiKoSolutions.Analyzers.Linguistics
{
    [TestFixture]
    public class AdjectiveFinderTests
    {
        [TestCase("Adaptability", ExpectedResult = "Adaptable")]
        [TestCase("adaptability", ExpectedResult = "Adaptable")]
        [TestCase("Activity", ExpectedResult = "Active")]
        [TestCase("activity", ExpectedResult = "Active")]
        [TestCase("Agility", ExpectedResult = "Agile")]
        [TestCase("agility", ExpectedResult = "Agile")]
        [TestCase("Authority", ExpectedResult = "Authoritative")]
        [TestCase("authority", ExpectedResult = "Authoritative")]
        [TestCase("Brutality", ExpectedResult = "Brutal")]
        [TestCase("brutality", ExpectedResult = "Brutal")]
        [TestCase("Capability", ExpectedResult = "Capable")]
        [TestCase("capability", ExpectedResult = "Capable")]
        [TestCase("Casualty", ExpectedResult = "Casual")]
        [TestCase("casualty", ExpectedResult = "Casual")]
        [TestCase("Clarity", ExpectedResult = "Clear")]
        [TestCase("clarity", ExpectedResult = "Clear")]
        [TestCase("Compatibility", ExpectedResult = "Compatible")]
        [TestCase("compatibility", ExpectedResult = "Compatible")]
        [TestCase("Complexity", ExpectedResult = "Complex")]
        [TestCase("complexity", ExpectedResult = "Complex")]
        [TestCase("Credibility", ExpectedResult = "Credible")]
        [TestCase("credibility", ExpectedResult = "Credible")]
        [TestCase("Creativity", ExpectedResult = "Creative")]
        [TestCase("creativity", ExpectedResult = "Creative")]
        [TestCase("Curiosity", ExpectedResult = "Curious")]
        [TestCase("curiosity", ExpectedResult = "Curious")]
        [TestCase("Dexterity", ExpectedResult = "Dexterous")]
        [TestCase("dexterity", ExpectedResult = "Dexterous")]
        [TestCase("Durability", ExpectedResult = "Durable")]
        [TestCase("durability", ExpectedResult = "Durable")]
        [TestCase("Elasticity", ExpectedResult = "Elastic")]
        [TestCase("elasticity", ExpectedResult = "Elastic")]
        [TestCase("Electricity", ExpectedResult = "Electric")]
        [TestCase("electricity", ExpectedResult = "Electric")]
        [TestCase("Equality", ExpectedResult = "Equal")]
        [TestCase("equality", ExpectedResult = "Equal")]
        [TestCase("Familiarity", ExpectedResult = "Familiar")]
        [TestCase("familiarity", ExpectedResult = "Familiar")]
        [TestCase("Fatality", ExpectedResult = "Fatal")]
        [TestCase("fatality", ExpectedResult = "Fatal")]
        [TestCase("Fertility", ExpectedResult = "Fertile")]
        [TestCase("fertility", ExpectedResult = "Fertile")]
        [TestCase("Flexibility", ExpectedResult = "Flexible")]
        [TestCase("flexibility", ExpectedResult = "Flexible")]
        [TestCase("Frivolity", ExpectedResult = "Frivolous")]
        [TestCase("frivolity", ExpectedResult = "Frivolous")]
        [TestCase("Hospitality", ExpectedResult = "Hospitable")]
        [TestCase("hospitality", ExpectedResult = "Hospitable")]
        [TestCase("Immensity", ExpectedResult = "Immense")]
        [TestCase("immensity", ExpectedResult = "Immense")]
        [TestCase("Impurity", ExpectedResult = "Impure")]
        [TestCase("impurity", ExpectedResult = "Impure")]
        [TestCase("Inactivity", ExpectedResult = "Inactive")]
        [TestCase("inactivity", ExpectedResult = "Inactive")]
        [TestCase("Inequality", ExpectedResult = "Unequal")]
        [TestCase("inequality", ExpectedResult = "Unequal")]
        [TestCase("Insanity", ExpectedResult = "Insane")]
        [TestCase("insanity", ExpectedResult = "Insane")]
        [TestCase("Intensity", ExpectedResult = "Intense")]
        [TestCase("intensity", ExpectedResult = "Intense")]
        [TestCase("Legality", ExpectedResult = "Legal")]
        [TestCase("legality", ExpectedResult = "Legal")]
        [TestCase("Legibility", ExpectedResult = "Legible")]
        [TestCase("legibility", ExpectedResult = "Legible")]
        [TestCase("Mobility", ExpectedResult = "Mobile")]
        [TestCase("mobility", ExpectedResult = "Mobile")]
        [TestCase("Morality", ExpectedResult = "Moral")]
        [TestCase("morality", ExpectedResult = "Moral")]
        [TestCase("Motility", ExpectedResult = "Motile")]
        [TestCase("motility", ExpectedResult = "Motile")]
        [TestCase("Nationality", ExpectedResult = "National")]
        [TestCase("nationality", ExpectedResult = "National")]
        [TestCase("Nobility", ExpectedResult = "Noble")]
        [TestCase("nobility", ExpectedResult = "Noble")]
        [TestCase("Normality", ExpectedResult = "Normal")]
        [TestCase("normality", ExpectedResult = "Normal")]
        [TestCase("Originality", ExpectedResult = "Original")]
        [TestCase("originality", ExpectedResult = "Original")]
        [TestCase("Personality", ExpectedResult = "Personal")]
        [TestCase("personality", ExpectedResult = "Personal")]
        [TestCase("Popularity", ExpectedResult = "Popular")]
        [TestCase("popularity", ExpectedResult = "Popular")]
        [TestCase("Possibility", ExpectedResult = "Possible")]
        [TestCase("possibility", ExpectedResult = "Possible")]
        [TestCase("Predictability", ExpectedResult = "Predictable")]
        [TestCase("predictability", ExpectedResult = "Predictable")]
        [TestCase("Productivity", ExpectedResult = "Productive")]
        [TestCase("productivity", ExpectedResult = "Productive")]
        [TestCase("Reality", ExpectedResult = "Real")]
        [TestCase("reality", ExpectedResult = "Real")]
        [TestCase("Reliability", ExpectedResult = "Reliable")]
        [TestCase("reliability", ExpectedResult = "Reliable")]
        [TestCase("Responsibility", ExpectedResult = "Responsible")]
        [TestCase("responsibility", ExpectedResult = "Responsible")]
        [TestCase("Sensibility", ExpectedResult = "Sensible")]
        [TestCase("sensibility", ExpectedResult = "Sensible")]
        [TestCase("Sensitivity", ExpectedResult = "Sensitive")]
        [TestCase("sensitivity", ExpectedResult = "Sensitive")]
        [TestCase("Sexuality", ExpectedResult = "Sexual")]
        [TestCase("sexuality", ExpectedResult = "Sexual")]
        [TestCase("Simplicity", ExpectedResult = "Simple")]
        [TestCase("simplicity", ExpectedResult = "Simple")]
        [TestCase("Spirituality", ExpectedResult = "Spiritual")]
        [TestCase("spirituality", ExpectedResult = "Spiritual")]
        [TestCase("Stability", ExpectedResult = "Stable")]
        [TestCase("stability", ExpectedResult = "Stable")]
        [TestCase("Sustainability", ExpectedResult = "Sustainable")]
        [TestCase("sustainability", ExpectedResult = "Sustainable")]
        [TestCase("Technicality", ExpectedResult = "Technical")]
        [TestCase("technicality", ExpectedResult = "Technical")]
        [TestCase("Totality", ExpectedResult = "Total")]
        [TestCase("totality", ExpectedResult = "Total")]
        [TestCase("Transformability", ExpectedResult = "Transformable")]
        [TestCase("transformability", ExpectedResult = "Transformable")]
        [TestCase("Universality", ExpectedResult = "Universal")]
        [TestCase("universality", ExpectedResult = "Universal")]
        [TestCase("Vanity", ExpectedResult = "Vain")]
        [TestCase("vanity", ExpectedResult = "Vain")]
        [TestCase("Versatility", ExpectedResult = "Versatile")]
        [TestCase("versatility", ExpectedResult = "Versatile")]
        [TestCase("Viability", ExpectedResult = "Viable")]
        [TestCase("viability", ExpectedResult = "Viable")]
        [TestCase("Visibility", ExpectedResult = "Visible")]
        [TestCase("visibility", ExpectedResult = "Visible")]
        [TestCase("Vitality", ExpectedResult = "Vital")]
        [TestCase("vitality", ExpectedResult = "Vital")]
        [TestCase("Vulnerability", ExpectedResult = "Vulnerable")]
        [TestCase("vulnerability", ExpectedResult = "Vulnerable")]
        [TestCase("Readiness", ExpectedResult = "Ready")]
        [TestCase("readiness", ExpectedResult = "Ready")]
        public string GetAdjectiveForNoun_returns_adjective_for_noun_in_upper_case_(string noun) => AdjectiveFinder.GetAdjectiveForNoun(noun, FirstWordAdjustment.StartUpperCase);

        [TestCase("Adaptability", ExpectedResult = "adaptable")]
        [TestCase("adaptability", ExpectedResult = "adaptable")]
        [TestCase("Activity", ExpectedResult = "active")]
        [TestCase("activity", ExpectedResult = "active")]
        [TestCase("Agility", ExpectedResult = "agile")]
        [TestCase("agility", ExpectedResult = "agile")]
        [TestCase("Authority", ExpectedResult = "authoritative")]
        [TestCase("authority", ExpectedResult = "authoritative")]
        [TestCase("Brutality", ExpectedResult = "brutal")]
        [TestCase("brutality", ExpectedResult = "brutal")]
        [TestCase("Capability", ExpectedResult = "capable")]
        [TestCase("capability", ExpectedResult = "capable")]
        [TestCase("Casualty", ExpectedResult = "casual")]
        [TestCase("casualty", ExpectedResult = "casual")]
        [TestCase("Clarity", ExpectedResult = "clear")]
        [TestCase("clarity", ExpectedResult = "clear")]
        [TestCase("Compatibility", ExpectedResult = "compatible")]
        [TestCase("compatibility", ExpectedResult = "compatible")]
        [TestCase("Complexity", ExpectedResult = "complex")]
        [TestCase("complexity", ExpectedResult = "complex")]
        [TestCase("Credibility", ExpectedResult = "credible")]
        [TestCase("credibility", ExpectedResult = "credible")]
        [TestCase("Creativity", ExpectedResult = "creative")]
        [TestCase("creativity", ExpectedResult = "creative")]
        [TestCase("Curiosity", ExpectedResult = "curious")]
        [TestCase("curiosity", ExpectedResult = "curious")]
        [TestCase("Dexterity", ExpectedResult = "dexterous")]
        [TestCase("dexterity", ExpectedResult = "dexterous")]
        [TestCase("Durability", ExpectedResult = "durable")]
        [TestCase("durability", ExpectedResult = "durable")]
        [TestCase("Elasticity", ExpectedResult = "elastic")]
        [TestCase("elasticity", ExpectedResult = "elastic")]
        [TestCase("Electricity", ExpectedResult = "electric")]
        [TestCase("electricity", ExpectedResult = "electric")]
        [TestCase("Equality", ExpectedResult = "equal")]
        [TestCase("equality", ExpectedResult = "equal")]
        [TestCase("Familiarity", ExpectedResult = "familiar")]
        [TestCase("familiarity", ExpectedResult = "familiar")]
        [TestCase("Fatality", ExpectedResult = "fatal")]
        [TestCase("fatality", ExpectedResult = "fatal")]
        [TestCase("Fertility", ExpectedResult = "fertile")]
        [TestCase("fertility", ExpectedResult = "fertile")]
        [TestCase("Flexibility", ExpectedResult = "flexible")]
        [TestCase("flexibility", ExpectedResult = "flexible")]
        [TestCase("Frivolity", ExpectedResult = "frivolous")]
        [TestCase("frivolity", ExpectedResult = "frivolous")]
        [TestCase("Hospitality", ExpectedResult = "hospitable")]
        [TestCase("hospitality", ExpectedResult = "hospitable")]
        [TestCase("Immensity", ExpectedResult = "immense")]
        [TestCase("immensity", ExpectedResult = "immense")]
        [TestCase("Impurity", ExpectedResult = "impure")]
        [TestCase("impurity", ExpectedResult = "impure")]
        [TestCase("Inactivity", ExpectedResult = "inactive")]
        [TestCase("inactivity", ExpectedResult = "inactive")]
        [TestCase("Inequality", ExpectedResult = "unequal")]
        [TestCase("inequality", ExpectedResult = "unequal")]
        [TestCase("Insanity", ExpectedResult = "insane")]
        [TestCase("insanity", ExpectedResult = "insane")]
        [TestCase("Intensity", ExpectedResult = "intense")]
        [TestCase("intensity", ExpectedResult = "intense")]
        [TestCase("Legality", ExpectedResult = "legal")]
        [TestCase("legality", ExpectedResult = "legal")]
        [TestCase("Legibility", ExpectedResult = "legible")]
        [TestCase("legibility", ExpectedResult = "legible")]
        [TestCase("Mobility", ExpectedResult = "mobile")]
        [TestCase("mobility", ExpectedResult = "mobile")]
        [TestCase("Morality", ExpectedResult = "moral")]
        [TestCase("morality", ExpectedResult = "moral")]
        [TestCase("Motility", ExpectedResult = "motile")]
        [TestCase("motility", ExpectedResult = "motile")]
        [TestCase("Nationality", ExpectedResult = "national")]
        [TestCase("nationality", ExpectedResult = "national")]
        [TestCase("Nobility", ExpectedResult = "noble")]
        [TestCase("nobility", ExpectedResult = "noble")]
        [TestCase("Normality", ExpectedResult = "normal")]
        [TestCase("normality", ExpectedResult = "normal")]
        [TestCase("Originality", ExpectedResult = "original")]
        [TestCase("originality", ExpectedResult = "original")]
        [TestCase("Personality", ExpectedResult = "personal")]
        [TestCase("personality", ExpectedResult = "personal")]
        [TestCase("Popularity", ExpectedResult = "popular")]
        [TestCase("popularity", ExpectedResult = "popular")]
        [TestCase("Possibility", ExpectedResult = "possible")]
        [TestCase("possibility", ExpectedResult = "possible")]
        [TestCase("Predictability", ExpectedResult = "predictable")]
        [TestCase("predictability", ExpectedResult = "predictable")]
        [TestCase("Productivity", ExpectedResult = "productive")]
        [TestCase("productivity", ExpectedResult = "productive")]
        [TestCase("Reality", ExpectedResult = "real")]
        [TestCase("reality", ExpectedResult = "real")]
        [TestCase("Reliability", ExpectedResult = "reliable")]
        [TestCase("reliability", ExpectedResult = "reliable")]
        [TestCase("Responsibility", ExpectedResult = "responsible")]
        [TestCase("responsibility", ExpectedResult = "responsible")]
        [TestCase("Sensibility", ExpectedResult = "sensible")]
        [TestCase("sensibility", ExpectedResult = "sensible")]
        [TestCase("Sensitivity", ExpectedResult = "sensitive")]
        [TestCase("sensitivity", ExpectedResult = "sensitive")]
        [TestCase("Sexuality", ExpectedResult = "sexual")]
        [TestCase("sexuality", ExpectedResult = "sexual")]
        [TestCase("Simplicity", ExpectedResult = "simple")]
        [TestCase("simplicity", ExpectedResult = "simple")]
        [TestCase("Spirituality", ExpectedResult = "spiritual")]
        [TestCase("spirituality", ExpectedResult = "spiritual")]
        [TestCase("Stability", ExpectedResult = "stable")]
        [TestCase("stability", ExpectedResult = "stable")]
        [TestCase("Sustainability", ExpectedResult = "sustainable")]
        [TestCase("sustainability", ExpectedResult = "sustainable")]
        [TestCase("Technicality", ExpectedResult = "technical")]
        [TestCase("technicality", ExpectedResult = "technical")]
        [TestCase("Totality", ExpectedResult = "total")]
        [TestCase("totality", ExpectedResult = "total")]
        [TestCase("Transformability", ExpectedResult = "transformable")]
        [TestCase("transformability", ExpectedResult = "transformable")]
        [TestCase("Universality", ExpectedResult = "universal")]
        [TestCase("universality", ExpectedResult = "universal")]
        [TestCase("Vanity", ExpectedResult = "vain")]
        [TestCase("vanity", ExpectedResult = "vain")]
        [TestCase("Versatility", ExpectedResult = "versatile")]
        [TestCase("versatility", ExpectedResult = "versatile")]
        [TestCase("Viability", ExpectedResult = "viable")]
        [TestCase("viability", ExpectedResult = "viable")]
        [TestCase("Visibility", ExpectedResult = "visible")]
        [TestCase("visibility", ExpectedResult = "visible")]
        [TestCase("Vitality", ExpectedResult = "vital")]
        [TestCase("vitality", ExpectedResult = "vital")]
        [TestCase("Vulnerability", ExpectedResult = "vulnerable")]
        [TestCase("vulnerability", ExpectedResult = "vulnerable")]
        [TestCase("Readiness", ExpectedResult = "ready")]
        [TestCase("readiness", ExpectedResult = "ready")]
        public string GetAdjectiveForNoun_returns_adjective_for_noun_in_lower_case_(string noun) => AdjectiveFinder.GetAdjectiveForNoun(noun, FirstWordAdjustment.StartLowerCase);

        [TestCase("Adaptable")]
        [TestCase("adaptable")]
        [TestCase("Active")]
        [TestCase("active")]
        [TestCase("Agile")]
        [TestCase("agile")]
        [TestCase("Authoritative")]
        [TestCase("authoritative")]
        [TestCase("Brutal")]
        [TestCase("brutal")]
        [TestCase("Capable")]
        [TestCase("capable")]
        [TestCase("Casual")]
        [TestCase("casual")]
        [TestCase("Clear")]
        [TestCase("clear")]
        [TestCase("Compatible")]
        [TestCase("compatible")]
        [TestCase("Complex")]
        [TestCase("complex")]
        [TestCase("Credible")]
        [TestCase("credible")]
        [TestCase("Creative")]
        [TestCase("creative")]
        [TestCase("Curious")]
        [TestCase("curious")]
        [TestCase("Dexterous")]
        [TestCase("dexterous")]
        [TestCase("Durable")]
        [TestCase("durable")]
        [TestCase("Elastic")]
        [TestCase("elastic")]
        [TestCase("Electric")]
        [TestCase("electric")]
        [TestCase("Equal")]
        [TestCase("equal")]
        [TestCase("Familiar")]
        [TestCase("familiar")]
        [TestCase("Fatal")]
        [TestCase("fatal")]
        [TestCase("Fertile")]
        [TestCase("fertile")]
        [TestCase("Flexible")]
        [TestCase("flexible")]
        [TestCase("Frivolous")]
        [TestCase("frivolous")]
        [TestCase("Hospitable")]
        [TestCase("hospitable")]
        [TestCase("Immense")]
        [TestCase("immense")]
        [TestCase("Impure")]
        [TestCase("impure")]
        [TestCase("Inactive")]
        [TestCase("inactive")]
        [TestCase("Unequal")]
        [TestCase("unequal")]
        [TestCase("Insane")]
        [TestCase("insane")]
        [TestCase("Intense")]
        [TestCase("intense")]
        [TestCase("Legal")]
        [TestCase("legal")]
        [TestCase("Legible")]
        [TestCase("legible")]
        [TestCase("Mobile")]
        [TestCase("mobile")]
        [TestCase("Moral")]
        [TestCase("moral")]
        [TestCase("Motile")]
        [TestCase("motile")]
        [TestCase("National")]
        [TestCase("national")]
        [TestCase("Normal")]
        [TestCase("normal")]
        [TestCase("Original")]
        [TestCase("original")]
        [TestCase("Personal")]
        [TestCase("personal")]
        [TestCase("Popular")]
        [TestCase("popular")]
        [TestCase("Possible")]
        [TestCase("possible")]
        [TestCase("Predictable")]
        [TestCase("predictable")]
        [TestCase("Productive")]
        [TestCase("productive")]
        [TestCase("Real")]
        [TestCase("real")]
        [TestCase("Reliable")]
        [TestCase("reliable")]
        [TestCase("Responsible")]
        [TestCase("responsible")]
        [TestCase("Sensible")]
        [TestCase("sensible")]
        [TestCase("Sensitive")]
        [TestCase("sensitive")]
        [TestCase("Sexual")]
        [TestCase("sexual")]
        [TestCase("Simple")]
        [TestCase("simple")]
        [TestCase("Spiritual")]
        [TestCase("spiritual")]
        [TestCase("Stable")]
        [TestCase("stable")]
        [TestCase("Sustainable")]
        [TestCase("sustainable")]
        [TestCase("Technical")]
        [TestCase("technical")]
        [TestCase("Total")]
        [TestCase("total")]
        [TestCase("Transformable")]
        [TestCase("transformable")]
        [TestCase("Universal")]
        [TestCase("universal")]
        [TestCase("Vain")]
        [TestCase("vain")]
        [TestCase("Versatile")]
        [TestCase("versatile")]
        [TestCase("Viable")]
        [TestCase("viable")]
        [TestCase("Visible")]
        [TestCase("visible")]
        [TestCase("Vital")]
        [TestCase("vital")]
        [TestCase("Vulnerable")]
        [TestCase("vulnerable")]
        [TestCase("Ready")]
        [TestCase("ready")]
        public void IsAdjectiveOrAdverb_returns_true_for_(string adjective) => Assert.That(AdjectiveFinder.IsAdjectiveOrAdverb(adjective), Is.True);

        [TestCase("File")]
        [TestCase("file")]
        [TestCase("Mile")]
        [TestCase("mile")]
        [TestCase("Cure")]
        [TestCase("cure")]
        public void IsAdjectiveOrAdverb_returns_false_for_(string adjective) => Assert.That(AdjectiveFinder.IsAdjectiveOrAdverb(adjective), Is.False);
    }
}