using System.Collections.Generic;
using System.Composition;
using System.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MiKoSolutions.Analyzers.Rules.Documentation
{
    [ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(MiKo_2022_CodeFixProvider)), Shared]
    public sealed class MiKo_2022_CodeFixProvider : ParameterDocumentationCodeFixProvider
    {
//// ncrunch: rdi off

        private static readonly string[] ReplacementMapKeys = CreatePhrases().ToArray();

        private static readonly Pair[] ReplacementMap = ReplacementMapKeys.ToArray(_ => new Pair(_));

        public override string FixableDiagnosticId => "MiKo_2022";

//// ncrunch: rdi default

        protected override XmlElementSyntax Comment(Document document, XmlElementSyntax comment, ParameterSyntax parameter, in int index, Diagnostic issue)
        {
            var preparedComment = PrepareComment(comment);
            var phrase = GetStartingPhraseProposal(issue);

            var contents = preparedComment.Content;

            switch (contents.Count)
            {
                case 0:
                    return CommentStartingWith(preparedComment, phrase + Constants.TODO + ".");

                case 1 when contents[0].IsWhiteSpaceOnlyText():
                    return comment.ReplaceNode(contents[0], XmlText(phrase + Constants.TODO + ".").WithLeadingXmlComment().WithTrailingXmlComment());

                default:
                    return CommentStartingWith(preparedComment, phrase);
            }
        }

        private static XmlElementSyntax PrepareComment(XmlElementSyntax comment) => Comment(comment, ReplacementMapKeys, ReplacementMap);

//// ncrunch: rdi off

        private static HashSet<string> CreatePhrases() => new HashSet<string>
                                                              {
                                                                  "A Flag indicating ",
                                                                  "A Flag that indicates ",
                                                                  "A Flag which indicates ",
                                                                  "A flag indicating ",
                                                                  "A flag that indicates ",
                                                                  "A flag which indicates ",
                                                                  "A value indicating ",
                                                                  "A value that indicates ",
                                                                  "A value which indicates ",
                                                                  "A variable that receives ",
                                                                  "A variable which receives ",
                                                                  "After return contains a flag indicating ",
                                                                  "After return contains a flag that indicates ",
                                                                  "After return contains a flag which indicates ",
                                                                  "After return contains a value indicating ",
                                                                  "After return contains a value that indicates ",
                                                                  "After return contains a value which indicates ",
                                                                  "After return provides a flag indicating ",
                                                                  "After return provides a flag that indicates ",
                                                                  "After return provides a flag which indicates ",
                                                                  "After return provides a value indicating ",
                                                                  "After return provides a value that indicates ",
                                                                  "After return provides a value which indicates ",
                                                                  "After return receives a flag indicating ",
                                                                  "After return receives a flag that indicates ",
                                                                  "After return receives a flag which indicates ",
                                                                  "After return receives a value indicating ",
                                                                  "After return receives a value that indicates ",
                                                                  "After return receives a value which indicates ",
                                                                  "After return, contains a flag indicating ",
                                                                  "After return, contains a flag that indicates ",
                                                                  "After return, contains a flag which indicates ",
                                                                  "After return, contains a value indicating ",
                                                                  "After return, contains a value that indicates ",
                                                                  "After return, contains a value which indicates ",
                                                                  "After return, provides a flag indicating ",
                                                                  "After return, provides a flag that indicates ",
                                                                  "After return, provides a flag which indicates ",
                                                                  "After return, provides a value indicating ",
                                                                  "After return, provides a value that indicates ",
                                                                  "After return, provides a value which indicates ",
                                                                  "After return, receives a flag indicating ",
                                                                  "After return, receives a flag that indicates ",
                                                                  "After return, receives a flag which indicates ",
                                                                  "After return, receives a value indicating ",
                                                                  "After return, receives a value that indicates ",
                                                                  "After return, receives a value which indicates ",
                                                                  "After successful return contains a flag indicating ",
                                                                  "After successful return contains a flag that indicates ",
                                                                  "After successful return contains a flag which indicates ",
                                                                  "After successful return contains a value indicating ",
                                                                  "After successful return contains a value that indicates ",
                                                                  "After successful return contains a value which indicates ",
                                                                  "After successful return provides a flag indicating ",
                                                                  "After successful return provides a flag that indicates ",
                                                                  "After successful return provides a flag which indicates ",
                                                                  "After successful return provides a value indicating ",
                                                                  "After successful return provides a value that indicates ",
                                                                  "After successful return provides a value which indicates ",
                                                                  "After successful return receives a flag indicating ",
                                                                  "After successful return receives a flag that indicates ",
                                                                  "After successful return receives a flag which indicates ",
                                                                  "After successful return receives a value indicating ",
                                                                  "After successful return receives a value that indicates ",
                                                                  "After successful return receives a value which indicates ",
                                                                  "After successful return, contains a flag indicating ",
                                                                  "After successful return, contains a flag that indicates ",
                                                                  "After successful return, contains a flag which indicates ",
                                                                  "After successful return, contains a value indicating ",
                                                                  "After successful return, contains a value that indicates ",
                                                                  "After successful return, contains a value which indicates ",
                                                                  "After successful return, provides a flag indicating ",
                                                                  "After successful return, provides a flag that indicates ",
                                                                  "After successful return, provides a flag which indicates ",
                                                                  "After successful return, provides a value indicating ",
                                                                  "After successful return, provides a value that indicates ",
                                                                  "After successful return, provides a value which indicates ",
                                                                  "After successful return, receives a flag indicating ",
                                                                  "After successful return, receives a flag that indicates ",
                                                                  "After successful return, receives a flag which indicates ",
                                                                  "After successful return, receives a value indicating ",
                                                                  "After successful return, receives a value that indicates ",
                                                                  "After successful return, receives a value which indicates ",
                                                                  "After return contains ",
                                                                  "After return indicates ",
                                                                  "After return provides ",
                                                                  "After return receives ",
                                                                  "After return, contains ",
                                                                  "After return, indicates ",
                                                                  "After return, provides ",
                                                                  "After return, receives ",
                                                                  "After successful return contains ",
                                                                  "After successful return indicates ",
                                                                  "After successful return provides ",
                                                                  "After successful return receives ",
                                                                  "After successful return, contains ",
                                                                  "After successful return, indicates ",
                                                                  "After successful return, provides ",
                                                                  "After successful return, receives ",
                                                                  "Contains ",
                                                                  "Flag indicating ",
                                                                  "Flag that indicates ",
                                                                  "Flag which indicates ",
                                                                  "Indicates ",
                                                                  "Indicating ",
                                                                  "If successful contains a flag indicating ",
                                                                  "If successful contains a flag that indicates ",
                                                                  "If successful contains a flag which indicates ",
                                                                  "If successful contains a value indicating ",
                                                                  "If successful contains a value that indicates ",
                                                                  "If successful contains a value which indicates ",
                                                                  "If successful provides a flag indicating ",
                                                                  "If successful provides a flag that indicates ",
                                                                  "If successful provides a flag which indicates ",
                                                                  "If successful provides a value indicating ",
                                                                  "If successful provides a value that indicates ",
                                                                  "If successful provides a value which indicates ",
                                                                  "If successful receives a flag indicating ",
                                                                  "If successful receives a flag that indicates ",
                                                                  "If successful receives a flag which indicates ",
                                                                  "If successful receives a value indicating ",
                                                                  "If successful receives a value that indicates ",
                                                                  "If successful receives a value which indicates ",
                                                                  "If successful contains ",
                                                                  "If successful indicates ",
                                                                  "If successful provides ",
                                                                  "If successful receives ",
                                                                  "If successful, provides a flag indicating ",
                                                                  "If successful, provides a flag that indicates ",
                                                                  "If successful, provides a flag which indicates ",
                                                                  "If successful, provides a value indicating ",
                                                                  "If successful, provides a value that indicates ",
                                                                  "If successful, provides a value which indicates ",
                                                                  "If successful, receives a flag indicating ",
                                                                  "If successful, receives a flag that indicates ",
                                                                  "If successful, receives a flag which indicates ",
                                                                  "If successful, receives a value indicating ",
                                                                  "If successful, receives a value that indicates ",
                                                                  "If successful, receives a value which indicates ",
                                                                  "If successful, contains ",
                                                                  "If successful, indicates ",
                                                                  "If successful, provides ",
                                                                  "If successful, receives ",
                                                                  "If successful, ",
                                                                  "If successful ",
                                                                  "If the method returns successfully ",
                                                                  "If the method returns successfully, contains ",
                                                                  "If the method returns successfully, indicates ",
                                                                  "If the method returns successfully, provides ",
                                                                  "If the method returns successfully, receives ",
                                                                  "If the method returns successfully, ",
                                                                  "If the method successfully returns ",
                                                                  "If the method successfully returns, contains ",
                                                                  "If the method successfully returns, indicates ",
                                                                  "If the method successfully returns, provides ",
                                                                  "If the method successfully returns, receives ",
                                                                  "If the method successfully returns, ",
                                                                  "If this method returns successfully ",
                                                                  "If this method returns successfully, contains ",
                                                                  "If this method returns successfully, indicates ",
                                                                  "If this method returns successfully, provides ",
                                                                  "If this method returns successfully, receives ",
                                                                  "If this method returns successfully, ",
                                                                  "If this method successfully returns ",
                                                                  "If this method successfully returns, contains ",
                                                                  "If this method successfully returns, indicates ",
                                                                  "If this method successfully returns, provides ",
                                                                  "If this method successfully returns, receives ",
                                                                  "If this method successfully returns, ",
                                                                  "If the method returns ",
                                                                  "If the method returns, contains ",
                                                                  "If the method returns, indicates ",
                                                                  "If the method returns, provides ",
                                                                  "If the method returns, receives ",
                                                                  "If the method returns, ",
                                                                  "If this method returns ",
                                                                  "If this method returns, contains ",
                                                                  "If this method returns, indicates ",
                                                                  "If this method returns, provides ",
                                                                  "If this method returns, receives ",
                                                                  "If this method returns, ",
                                                                  "On return contains a flag indicating ",
                                                                  "On return contains a flag that indicates ",
                                                                  "On return contains a flag which indicates ",
                                                                  "On return contains a value indicating ",
                                                                  "On return contains a value that indicates ",
                                                                  "On return contains a value which indicates ",
                                                                  "On return provides a flag indicating ",
                                                                  "On return provides a flag that indicates ",
                                                                  "On return provides a flag which indicates ",
                                                                  "On return provides a value indicating ",
                                                                  "On return provides a value that indicates ",
                                                                  "On return provides a value which indicates ",
                                                                  "On return receives a flag indicating ",
                                                                  "On return receives a flag that indicates ",
                                                                  "On return receives a flag which indicates ",
                                                                  "On return receives a value indicating ",
                                                                  "On return receives a value that indicates ",
                                                                  "On return receives a value which indicates ",
                                                                  "On return contains ",
                                                                  "On return indicates ",
                                                                  "On return provides ",
                                                                  "On return receives ",
                                                                  "On return, contains a flag indicating ",
                                                                  "On return, contains a flag that indicates ",
                                                                  "On return, contains a flag which indicates ",
                                                                  "On return, contains a value indicating ",
                                                                  "On return, contains a value that indicates ",
                                                                  "On return, contains a value which indicates ",
                                                                  "On return, provides a flag indicating ",
                                                                  "On return, provides a flag that indicates ",
                                                                  "On return, provides a flag which indicates ",
                                                                  "On return, provides a value indicating ",
                                                                  "On return, provides a value that indicates ",
                                                                  "On return, provides a value which indicates ",
                                                                  "On return, receives a flag indicating ",
                                                                  "On return, receives a flag that indicates ",
                                                                  "On return, receives a flag which indicates ",
                                                                  "On return, receives a value indicating ",
                                                                  "On return, receives a value that indicates ",
                                                                  "On return, receives a value which indicates ",
                                                                  "On return, contains ",
                                                                  "On return, indicates ",
                                                                  "On return, provides ",
                                                                  "On return, receives ",
                                                                  "On return, ",
                                                                  "On return ",
                                                                  "On success, contains ",
                                                                  "On success, indicates ",
                                                                  "On success, provides ",
                                                                  "On success, receives ",
                                                                  "On success, ",
                                                                  "On success contains ",
                                                                  "On success indicates ",
                                                                  "On success provides ",
                                                                  "On success receives ",
                                                                  "On success ",
                                                                  "On successful return contains a flag indicating ",
                                                                  "On successful return contains a flag that indicates ",
                                                                  "On successful return contains a flag which indicates ",
                                                                  "On successful return contains a value indicating ",
                                                                  "On successful return contains a value that indicates ",
                                                                  "On successful return contains a value which indicates ",
                                                                  "On successful return provides a flag indicating ",
                                                                  "On successful return provides a flag that indicates ",
                                                                  "On successful return provides a flag which indicates ",
                                                                  "On successful return provides a value indicating ",
                                                                  "On successful return provides a value that indicates ",
                                                                  "On successful return provides a value which indicates ",
                                                                  "On successful return receives a flag indicating ",
                                                                  "On successful return receives a flag that indicates ",
                                                                  "On successful return receives a flag which indicates ",
                                                                  "On successful return receives a value indicating ",
                                                                  "On successful return receives a value that indicates ",
                                                                  "On successful return receives a value which indicates ",
                                                                  "On successful return contains ",
                                                                  "On successful return indicates ",
                                                                  "On successful return provides ",
                                                                  "On successful return receives ",
                                                                  "On successful return, provides a flag indicating ",
                                                                  "On successful return, provides a flag that indicates ",
                                                                  "On successful return, provides a flag which indicates ",
                                                                  "On successful return, provides a value indicating ",
                                                                  "On successful return, provides a value that indicates ",
                                                                  "On successful return, provides a value which indicates ",
                                                                  "On successful return, receives a flag indicating ",
                                                                  "On successful return, receives a flag that indicates ",
                                                                  "On successful return, receives a flag which indicates ",
                                                                  "On successful return, receives a value indicating ",
                                                                  "On successful return, receives a value that indicates ",
                                                                  "On successful return, receives a value which indicates ",
                                                                  "On successful return, contains ",
                                                                  "On successful return, indicates ",
                                                                  "On successful return, provides ",
                                                                  "On successful return, receives ",
                                                                  "On successful return, ",
                                                                  "On successful return ",
                                                                  "Out parameter that contains ",
                                                                  "Out parameter that provides ",
                                                                  "Out parameter that receives ",
                                                                  "Out parameter that returns ",
                                                                  "Out parameter which contains ",
                                                                  "Out parameter which provides ",
                                                                  "Out parameter which receives ",
                                                                  "Out parameter which returns ",
                                                                  "Out parameter, contains ",
                                                                  "Out parameter, provides ",
                                                                  "Out parameter, receives ",
                                                                  "Out parameter, returns ",
                                                                  "OUT - ",
                                                                  "OUT -",
                                                                  "OUT ",
                                                                  "OUT: ",
                                                                  "Out - ",
                                                                  "Out -",
                                                                  "Out ",
                                                                  "Out: ",
                                                                  "Provides ",
                                                                  "Receives ",
                                                                  "Return ",
                                                                  "Returned on ",
                                                                  "Returned when ",
                                                                  "Returns ",
                                                                  "Specifies ",
                                                                  "To return ",
                                                                  "Value indicating ",
                                                                  "Value that indicates ",
                                                                  "Value which indicates ",
                                                                  "When successful contains a flag indicating ",
                                                                  "When successful contains a flag that indicates ",
                                                                  "When successful contains a flag which indicates ",
                                                                  "When successful contains a value indicating ",
                                                                  "When successful contains a value that indicates ",
                                                                  "When successful contains a value which indicates ",
                                                                  "When successful provides a flag indicating ",
                                                                  "When successful provides a flag that indicates ",
                                                                  "When successful provides a flag which indicates ",
                                                                  "When successful provides a value indicating ",
                                                                  "When successful provides a value that indicates ",
                                                                  "When successful provides a value which indicates ",
                                                                  "When successful receives a flag indicating ",
                                                                  "When successful receives a flag that indicates ",
                                                                  "When successful receives a flag which indicates ",
                                                                  "When successful receives a value indicating ",
                                                                  "When successful receives a value that indicates ",
                                                                  "When successful receives a value which indicates ",
                                                                  "When successful contains ",
                                                                  "When successful indicates ",
                                                                  "When successful provides ",
                                                                  "When successful receives ",
                                                                  "When successful ",
                                                                  "When successful, provides a flag indicating ",
                                                                  "When successful, provides a flag that indicates ",
                                                                  "When successful, provides a flag which indicates ",
                                                                  "When successful, provides a value indicating ",
                                                                  "When successful, provides a value that indicates ",
                                                                  "When successful, provides a value which indicates ",
                                                                  "When successful, receives a flag indicating ",
                                                                  "When successful, receives a flag that indicates ",
                                                                  "When successful, receives a flag which indicates ",
                                                                  "When successful, receives a value indicating ",
                                                                  "When successful, receives a value that indicates ",
                                                                  "When successful, receives a value which indicates ",
                                                                  "When successful, contains ",
                                                                  "When successful, indicates ",
                                                                  "When successful, provides ",
                                                                  "When successful, receives ",
                                                                  "When successful, ",
                                                                  "When the method returns, contains ",
                                                                  "When the method returns, indicates ",
                                                                  "When the method returns, provides ",
                                                                  "When the method returns, receives ",
                                                                  "When the method returns, ",
                                                                  "When this method returns, contains ",
                                                                  "When this method returns, indicates ",
                                                                  "When this method returns, provides ",
                                                                  "When this method returns, receives ",
                                                                  "When this method returns, ",
                                                                  "When the method returns successfully ",
                                                                  "When the method returns successfully, contains ",
                                                                  "When the method returns successfully, indicates ",
                                                                  "When the method returns successfully, provides ",
                                                                  "When the method returns successfully, receives ",
                                                                  "When the method returns successfully, ",
                                                                  "When the method successfully returns ",
                                                                  "When the method successfully returns, contains ",
                                                                  "When the method successfully returns, indicates ",
                                                                  "When the method successfully returns, provides ",
                                                                  "When the method successfully returns, receives ",
                                                                  "When the method successfully returns, ",
                                                                  "When this method returns successfully ",
                                                                  "When this method returns successfully, contains ",
                                                                  "When this method returns successfully, indicates ",
                                                                  "When this method returns successfully, provides ",
                                                                  "When this method returns successfully, receives ",
                                                                  "When this method returns successfully, ",
                                                                  "When this method successfully returns ",
                                                                  "When this method successfully returns, contains ",
                                                                  "When this method successfully returns, indicates ",
                                                                  "When this method successfully returns, provides ",
                                                                  "When this method successfully returns, receives ",
                                                                  "When this method successfully returns, ",
                                                                  "When the method returns ",
                                                                  "When this method returns ",
                                                                  "Will be ",
                                                                  "Will contain ",
                                                                  "Will provide ",
                                                                  "Will receive ",
                                                                  "Will return ",
                                                                  "[OUT] parameter that contains ",
                                                                  "[OUT] parameter that provides ",
                                                                  "[OUT] parameter that receives ",
                                                                  "[OUT] parameter that returns ",
                                                                  "[Out] parameter that contains ",
                                                                  "[Out] parameter that provides ",
                                                                  "[Out] parameter that receives ",
                                                                  "[Out] parameter that returns ",
                                                                  "[out] parameter that contains ",
                                                                  "[out] parameter that provides ",
                                                                  "[out] parameter that receives ",
                                                                  "[out] parameter that returns ",
                                                                  "[OUT] parameter which contains ",
                                                                  "[OUT] parameter which provides ",
                                                                  "[OUT] parameter which receives ",
                                                                  "[OUT] parameter which returns ",
                                                                  "[Out] parameter which contains ",
                                                                  "[Out] parameter which provides ",
                                                                  "[Out] parameter which receives ",
                                                                  "[Out] parameter which returns ",
                                                                  "[out] parameter which contains ",
                                                                  "[out] parameter which provides ",
                                                                  "[out] parameter which receives ",
                                                                  "[out] parameter which returns ",
                                                                  "[OUT] parameter, contains ",
                                                                  "[OUT] parameter, provides ",
                                                                  "[OUT] parameter, receives ",
                                                                  "[OUT] parameter, returns ",
                                                                  "[Out] parameter, contains ",
                                                                  "[Out] parameter, provides ",
                                                                  "[Out] parameter, receives ",
                                                                  "[Out] parameter, returns ",
                                                                  "[out] parameter, contains ",
                                                                  "[out] parameter, provides ",
                                                                  "[out] parameter, receives ",
                                                                  "[out] parameter, returns ",
                                                                  "[OUT] ",
                                                                  "[Out] ",
                                                                  "[out] ",
                                                                  "[OUT]: ",
                                                                  "[Out]: ",
                                                                  "[out]: ",
                                                                  "flag indicating ",
                                                                  "flag that indicates ",
                                                                  "flag which indicates ",
                                                                  "out parameter that contains ",
                                                                  "out parameter that provides ",
                                                                  "out parameter that receives ",
                                                                  "out parameter that returns ",
                                                                  "out parameter which contains ",
                                                                  "out parameter which provides ",
                                                                  "out parameter which receives ",
                                                                  "out parameter which returns ",
                                                                  "out parameter, contains ",
                                                                  "out parameter, provides ",
                                                                  "out parameter, receives ",
                                                                  "out parameter, returns ",
                                                                  "out - ",
                                                                  "out -",
                                                                  "out ",
                                                                  "out: ",
                                                                  "value indicating ",
                                                                  "value that indicates ",
                                                                  "value which indicates ",
                                                                  "will contain ",
                                                                  "will provide ",
                                                                  "will receive ",
                                                                  "will return ",
                                                                  "return ",
                                                                  "returns ",
                                                              };

//// ncrunch: rdi default
    }
}